name: Shell Script Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: List Repo Files
          run: ls -lrta
        
        - name: Executing Shell Script
          run: ./ascii-script1.sh