name: Multi Job workflow

on: push

jobs:
    Build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
          
      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for Cover..., I am a DRAGON" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

    test_job_2:
      needs: Build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
        
      - name: Search for "dragon" in dragon.txt
        run:  grep -i "dragon" dragon.txt

    Deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Read File
          run: cat dragon.txt
          
        - name: Deploy
          run: echo Deploying .... ... ... ...
      